export const SIGNIN = 'SIGNIN';
export const ADD_AUTH = 'ADD_AUTH';
export const SUBMIT_TOKEN = 'SUBMIT_TOKEN';
export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SUBMIT_TOKEN_ERROR = 'SUBMIT_TOKEN_ERROR';
export const LOADING_FALSE = 'LOADING_FALSE';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';