export const SIGNIN = 'SIGNIN';
export const ADD_AUTH = 'ADD_AUTH';
export const SUBMIT_TOKEN = 'SUBMIT_TOKEN';
export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SUBMIT_TOKEN_ERROR = 'SUBMIT_TOKEN_ERROR';
export const LOADING_FALSE = 'LOADING_FALSE';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const CHECKBOX = 'CHECKBOX';



//provider
//==========================
//services
export const PROVIDER_SERVICE_VALUE = "PROVIDER_SERVICE_VALUE";
export const PROVIDER_CREATE_SERVICE_LOADER = "PROVIDER_CREATE_SERVICE_LOADER";
export const PROVIDER_CREATE_SERVICE = "PROVIDER_CREATE_SERVICE";
export const PROVIDER_DISPLAY_SERVICE_LOADER = "PROVIDER_DISPLAY_SERVICE_LOADER";
export const PROVIDER_DIPLAY_SERVICE_LIST = "PROVIDER_DISPLAY_SERVICE_LIST";
export const PROVIDER_DELETE_SERVICE_LIST = "PROVIDER_DELETE_SERVICE_LIST";
export const PROVIDER_UPDATE_SERVICE_LIST = "PROVIDER_UPDATE_SERVICE_LIST";

//statues
export const PROVIDER_LISTSTATUS_LOADER = "PROVIDER_LISTSTATUS_LOADER";
export const PROVIDER_STATUS_DETAILS = "PROVIDER_STATUS_DETAILS";
export const PROVIDER_STATUS_UPDATE_LOADER = "PROVIDER_STATUS_UPDATE_LOADER"
export const PROVIDER_STATUS_UPDATE = "PROVIDER_STATUS_UPDATE";
export const PROCIDER_STATUS_VALUE = "PROVIDER_STATUS_VALUE";
export const PROVIDER_STATUS_REFRESH = "PROVIDER_STATUS_REFRESH";